server:
  port: 8085
spring:
  cloud:
    stream:
      defaultBinder: rabbit
      bindings:
        single-message:
          destination: single.message.topic
          contentType: application/json
          group: amqp-sink
